import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Modal from "@/components/Modal";
import Login from "@/components/Login";
import SessionProvider from "@/components/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trello Clone",
  description: "Generated by Roihan",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#F5F6F8]`}>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <>
              {children}
              <Modal />
            </>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
